'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace NotificationSystem.Properties


    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As NotificationSystem.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New NotificationSystem.Properties.Settings())), NotificationSystem.Properties.Settings)

        Public Shared ReadOnly Property [Default] As NotificationSystem.Properties.Settings
            Get
                Return NotificationSystem.Properties.Settings.defaultInstance
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("relay.rc.notifications")>
        Public ReadOnly Property EmailSmtpClient As String
            Get
                Return CStr(Me("EmailSmtpClient"))
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public ReadOnly Property EmailCc As String
            Get
                Return CStr(Me("EmailCc"))
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public ReadOnly Property EmailBcc As String
            Get
                Return CStr(Me("EmailBcc"))
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("Omega.Fullard@RC.gamail")>
        Public ReadOnly Property WebAdmin As String
            Get
                Return CStr(Me("WebAdmin"))
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("ERROR")>
        Public ReadOnly Property EmailBodyTitle As String
            Get
                Return CStr(Me("EmailBodyTitle"))
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("NotificationSystem ERROR")>
        Public ReadOnly Property EmailFrom As String
            Get
                Return CStr(Me("EmailFrom"))
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("Omega Fullard")>
        Public ReadOnly Property Admins As String
            Get
                Return CStr(Me("Admins"))
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public ReadOnly Property EmailTo As String
            Get
                Return CStr(Me("EmailTo"))
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public ReadOnly Property EmailSubject As String
            Get
                Return CStr(Me("EmailSubject"))
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public ReadOnly Property SmtpServerID As String
            Get
                Return CStr(Me("SmtpServerID"))
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString)>
        <Global.System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\mssqlLocalDB;Initial Catalog=NotificationSystem;Integrated " & "Security=True;")>
        Public ReadOnly Property NotificationSystemConnectionString1 As String
            Get
                Return CStr(Me("NotificationSystemConnectionString1"))
            End Get
        End Property
    End Class
End Namespace
