//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class ctrAgent_Find
{

	/// <summary>
	/// lblAgentID control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Label lblAgentID;

	/// <summary>
	/// lblStartDate control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::Telerik.Web.UI.RadLabel lblStartDate;

	/// <summary>
	/// lblTroubleTicketNo control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::Telerik.Web.UI.RadLabel lblTroubleTicketNo;

	/// <summary>
	/// lblTitle control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::Telerik.Web.UI.RadLabel lblTitle;

	/// <summary>
	/// lblSalary control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::Telerik.Web.UI.RadLabel lblSalary;

	/// <summary>
	/// lblFN control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::Telerik.Web.UI.RadLabel lblFN;

	/// <summary>
	/// lblLN control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::Telerik.Web.UI.RadLabel lblLN;

	/// <summary>
	/// lblEmail control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::Telerik.Web.UI.RadLabel lblEmail;

	/// <summary>
	/// lblPhone control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::Telerik.Web.UI.RadLabel lblPhone;

	/// <summary>
	/// lblFax control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::Telerik.Web.UI.RadLabel lblFax;
}
