//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class ctrTroubleTicketReq_Find
{

	/// <summary>
	/// lblTroubleTicketNo control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Label lblTroubleTicketNo;

	/// <summary>
	/// lblSearchResult control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Label lblSearchResult;

	/// <summary>
	/// lblCustomerID control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::Telerik.Web.UI.RadLabel lblCustomerID;

	/// <summary>
	/// lblAgentID control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::Telerik.Web.UI.RadLabel lblAgentID;

	/// <summary>
	/// lblStatus control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::Telerik.Web.UI.RadLabel lblStatus;

	/// <summary>
	/// lblDueDate control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::Telerik.Web.UI.RadLabel lblDueDate;

	/// <summary>
	/// lblRequestDate control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::Telerik.Web.UI.RadLabel lblRequestDate;

	/// <summary>
	/// lblType control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::Telerik.Web.UI.RadLabel lblType;
}
