//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class ctrTroubleTicketReq_Update
{

	/// <summary>
	/// lblResult control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Label lblResult;

	/// <summary>
	/// Table1 control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Table Table1;

	/// <summary>
	/// txtcustomerid control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.TextBox txtcustomerid;

	/// <summary>
	/// valRequiredFieldID control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.RequiredFieldValidator valRequiredFieldID;

	/// <summary>
	/// Required_ID control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::AjaxControlToolkit.ValidatorCalloutExtender Required_ID;

	/// <summary>
	/// txtAgentID control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.TextBox txtAgentID;

	/// <summary>
	/// txttroubleticketno control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.TextBox txttroubleticketno;

	/// <summary>
	/// cmbStatus control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::Telerik.Web.UI.RadMultiColumnComboBox cmbStatus;

	/// <summary>
	/// valRequiredStatus control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.RequiredFieldValidator valRequiredStatus;

	/// <summary>
	/// Required_cmbStatus control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::AjaxControlToolkit.ValidatorCalloutExtender Required_cmbStatus;

	/// <summary>
	/// cmbType control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::Telerik.Web.UI.RadMultiColumnComboBox cmbType;

	/// <summary>
	/// valcmbType control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.RequiredFieldValidator valcmbType;

	/// <summary>
	/// required_cmbType control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::AjaxControlToolkit.ValidatorCalloutExtender required_cmbType;

	/// <summary>
	/// btnCancel control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Button btnCancel;

	/// <summary>
	/// btnUpdate control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Button btnUpdate;
}
