'----------------------
' <auto-generated>
'     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
' </auto-generated>
'----------------------



Namespace NotificationSystem







End Namespace
