'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace NotificationSystem.NotificationSystem.Web

    Partial Public Class Customer

        '''<summary>
        '''Table1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table1 As Global.System.Web.UI.WebControls.Table

        '''<summary>
        '''Panel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''defaultuser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents defaultuser As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''ctrCustomer_Search control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrCustomer_Search As Global.ctrCustomer_Search

        '''<summary>
        '''ctrCustomer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrCustomer As Global.NotificationSystem.NotificationSystem.Web.ctrCustomer
    End Class
End Namespace
