'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Namespace TelerikWebSite1
    Public Partial Class ListView

        ''' <summary>
        ''' JumbotronLayout control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected JumbotronLayout As Global.Telerik.Web.UI.RadPageLayout

        ''' <summary>
        ''' RadButton0 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected RadButton0 As Global.Telerik.Web.UI.RadButton

        ''' <summary>
        ''' RadListViewImages control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected RadListViewImages As Global.Telerik.Web.UI.RadListView

        ''' <summary>
        ''' RadListViewArticles control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected RadListViewArticles As Global.Telerik.Web.UI.RadListView

        ''' <summary>
        ''' RadLightBoxImageDetails control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected RadLightBoxImageDetails As Global.Telerik.Web.UI.RadLightBox
    End Class
End Namespace
