'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace NotificationSystem.NotificationSystem.Web


    Public Partial Class MasterPage

        ''' <summary>
        ''' head control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected head As Global.System.Web.UI.WebControls.ContentPlaceHolder

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' NavigationMenu control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected NavigationMenu As Global.System.Web.UI.WebControls.Menu

        ''' <summary>
        ''' ContentPlaceHolder1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ContentPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder

        ''' <summary>
        ''' ContentPlaceHolder2 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ContentPlaceHolder2 As Global.System.Web.UI.WebControls.ContentPlaceHolder

        ''' <summary>
        ''' ContentPlaceHolder3 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ContentPlaceHolder3 As Global.System.Web.UI.WebControls.ContentPlaceHolder
    End Class
End Namespace
