'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace NotificationSystem.NotificationSystem.Web


    Public Partial Class rptCustomer

        ''' <summary>
        ''' Table1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Table1 As Global.System.Web.UI.WebControls.Table

        ''' <summary>
        ''' ctrCustomer_Search control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ctrCustomer_Search As Global.ctrCustomer_Search

        ''' <summary>
        ''' ReportViewer1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ReportViewer1 As Global.Microsoft.Reporting.WebForms.ReportViewer
    End Class
End Namespace
