'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace NotificationSystem.NotificationSystem.Web


    Public Partial Class TicketDetails

        ''' <summary>
        ''' issue2 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected issue2 As Global.System.Web.UI.WebControls.Image

        ''' <summary>
        ''' Table1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Table1 As Global.System.Web.UI.WebControls.Table

        ''' <summary>
        ''' ctrTroubleTicketReq_Search control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ctrTroubleTicketReq_Search As Global.ctrTroubleTicketReq_Search

        ''' <summary>
        ''' TextBox5 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected TextBox5 As Global.System.Web.UI.WebControls.TextBox

        ''' <summary>
        ''' TextBox5_CalendarExtender control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected TextBox5_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

        ''' <summary>
        ''' TextBox6 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected TextBox6 As Global.System.Web.UI.WebControls.TextBox

        ''' <summary>
        ''' TextBox6_CalendarExtender control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected TextBox6_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

        ''' <summary>
        ''' Button2 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Button2 As Global.System.Web.UI.WebControls.Button

        ''' <summary>
        ''' ctrTroubleTicketReq control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ctrTroubleTicketReq As Global.NotificationSystem.NotificationSystem.Web.ctrTroubleTicketReq
    End Class
End Namespace
