'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace NotificationSystem.NotificationSystem.Web


    Public Partial Class TicketMgt

        ''' <summary>
        ''' Issues control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Issues As Global.System.Web.UI.WebControls.Image

        ''' <summary>
        ''' FileUpload1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected FileUpload1 As Global.System.Web.UI.WebControls.FileUpload

        ''' <summary>
        ''' TextBox1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected TextBox1 As Global.System.Web.UI.WebControls.TextBox

        ''' <summary>
        ''' LinkButton4 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected LinkButton4 As Global.System.Web.UI.WebControls.LinkButton

        ''' <summary>
        ''' Button1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Button1 As Global.System.Web.UI.WebControls.Button

        ''' <summary>
        ''' TextBox2 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected TextBox2 As Global.System.Web.UI.WebControls.TextBox

        ''' <summary>
        ''' DropDownList2 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected DropDownList2 As Global.System.Web.UI.WebControls.DropDownList

        ''' <summary>
        ''' DropDownList1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected DropDownList1 As Global.System.Web.UI.WebControls.DropDownList

        ''' <summary>
        ''' Button2 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Button2 As Global.System.Web.UI.WebControls.Button

        ''' <summary>
        ''' Button3 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Button3 As Global.System.Web.UI.WebControls.Button

        ''' <summary>
        ''' Button4 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Button4 As Global.System.Web.UI.WebControls.Button

        ''' <summary>
        ''' GridView1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected GridView1 As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
