'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------



Public Partial Class TroubleTicketReq_Update

    ''' <summary>
    ''' ScriptManager1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ScriptManager1 As Global.System.Web.UI.ScriptManager

    ''' <summary>
    ''' Table1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected Table1 As Global.System.Web.UI.WebControls.Table

    ''' <summary>
    ''' Panel1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected Panel1 As Global.System.Web.UI.WebControls.Panel

    ''' <summary>
    ''' issue1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected issue1 As Global.System.Web.UI.WebControls.Image

    ''' <summary>
    ''' ctrSearch_TTR_Update control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ctrSearch_TTR_Update As Global.NotificationSystem.NotificationSystem.Web.Controls_Search.ctrSearch_TTR_Update

    ''' <summary>
    ''' NavigationMenu control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected NavigationMenu As Global.System.Web.UI.WebControls.Menu

    ''' <summary>
    ''' ctrTroubleTicketReq_Update control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ctrTroubleTicketReq_Update As Global.ctrTroubleTicketReq_Update
End Class
