'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------



Public Partial Class TroubleTicketReq_Find

    ''' <summary>
    ''' Table1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected Table1 As Global.System.Web.UI.WebControls.Table

    ''' <summary>
    ''' Panel1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected Panel1 As Global.System.Web.UI.WebControls.Panel

    ''' <summary>
    ''' issue2 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected issue2 As Global.System.Web.UI.WebControls.Image

    ''' <summary>
    ''' ctrTroubleTicketReq_Search control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ctrTroubleTicketReq_Search As Global.ctrTroubleTicketReq_Search

    ''' <summary>
    ''' NavigationMenu control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected NavigationMenu As Global.System.Web.UI.WebControls.Menu

    ''' <summary>
    ''' ctrTroubleTicketReq_Find control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ctrTroubleTicketReq_Find As Global.ctrTroubleTicketReq_Find
End Class
