'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace NotificationSystem.NotificationSystem.Web


    Public Partial Class UserRegistration

        ''' <summary>
        ''' ScriptManager1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ScriptManager1 As Global.System.Web.UI.ScriptManager

        ''' <summary>
        ''' customerreg control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected customerreg As Global.System.Web.UI.WebControls.Image

        ''' <summary>
        ''' CustomerID control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected CustomerID As Global.System.Web.UI.WebControls.TextBox

        ''' <summary>
        ''' FirstN control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected FirstN As Global.System.Web.UI.WebControls.TextBox

        ''' <summary>
        ''' LastN control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected LastN As Global.System.Web.UI.WebControls.TextBox

        ''' <summary>
        ''' TextBox3 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected TextBox3 As Global.System.Web.UI.WebControls.TextBox

        ''' <summary>
        ''' TextBox4 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected TextBox4 As Global.System.Web.UI.WebControls.TextBox

        ''' <summary>
        ''' Address control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Address As Global.System.Web.UI.WebControls.TextBox

        ''' <summary>
        ''' TextBox6 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected TextBox6 As Global.System.Web.UI.WebControls.TextBox

        ''' <summary>
        ''' DropDownList1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected DropDownList1 As Global.System.Web.UI.WebControls.DropDownList

        ''' <summary>
        ''' TextBox11 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected TextBox11 As Global.System.Web.UI.WebControls.TextBox

        ''' <summary>
        ''' TextBox8 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected TextBox8 As Global.System.Web.UI.WebControls.TextBox

        ''' <summary>
        ''' TextBox9 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected TextBox9 As Global.System.Web.UI.WebControls.TextBox

        ''' <summary>
        ''' Button2 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Button2 As Global.System.Web.UI.WebControls.Button

        ''' <summary>
        ''' logo control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected logo As Global.System.Web.UI.WebControls.Image
    End Class
End Namespace
