'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace NotificationSystem.NotificationSystem.Web


    Public Partial Class UserViewProfile

        ''' <summary>
        ''' users control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected users As Global.System.Web.UI.WebControls.Image

        ''' <summary>
        ''' Label1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Label1 As Global.System.Web.UI.WebControls.Label

        ''' <summary>
        ''' TextBox3 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected TextBox3 As Global.System.Web.UI.WebControls.TextBox

        ''' <summary>
        ''' TextBox1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected TextBox1 As Global.System.Web.UI.WebControls.TextBox

        ''' <summary>
        ''' Button1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Button1 As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
